<?php /** @var $block \Snenko\NewsBlock\Block\Widget\Banner */ ?>
<?php if($items = $block->getItems()): ?>
<?php $locationNumbers = ["1","2","3","4","5"];?>

    <div class="actions-preview">
        <div class="container">
            <h2 class="_title">
                <span><?php echo $block->getTitle(); ?></span>
            </h2>

            <div class="actions-preview__wrap">
                <div class="_scroller">
                    <ul>

                    <?php foreach ($locationNumbers as $locationNumber):?>
                        <?php
                            /** @var Snenko\NewsBlock\Model\Posts $data */
                            $data = $block->getLocationData($locationNumber);
                        ?>
                        <?php $imageUrl = isset($data['image']) && $data['image']? $block->getMediaUrl($data['image']) :null; ?>
                        <?php $labelContent = isset($data['label_content'])?$data['label_content']:null; ?>
                        <?php $name = isset($data['name'])?$data['name']:null; ?>
                        <?php $description = isset($data['description'])?$data['description']:null; ?>
                        <?php $linkUrl = isset($data['link_url'])?$data['link_url']:null?:"#"; ?>
                        <li class="actions-preview-item">
                            <a href="<?php echo $linkUrl; ?>" style="background-image: url(<?php echo $imageUrl; ?>)">
                                <?php if($labelContent): ?>
                                    <div>
                                        <?php echo $labelContent; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if($name): ?>
                                    <h3>
                                        <?php echo $name; ?>
                                    </h3>
                                <?php endif; ?>

                                <?php if($description): ?>
                                    <?php echo $description; ?>
                                <?php endif; ?>
                            </a>
                        </li>
                    <?php endforeach; ?>

                    </ul>
                </div>
            </div>

            <?php if($showMoreLabel = $block->getShowMoreLabel()): ?>
                <div class="cta">
                    <a href="<?php echo $block->getShowMoreUrl(); ?>">
                        <span><?php echo $showMoreLabel; ?></span>
                    </a>
                </div>
            <?php endif; ?>

        </div>
    </div>

    <script type="text/javascript">
		require([
			'jquery',
			'owl.carousel/owl.carousel.min'
		], function ($) {
            if ($(window).width() <= 767) {
                $("._scroller ul").owlCarousel({
                    nav: false,
                    dots: true,
                    responsive: {
                        0: {
                            items: 1
                        }
                    }
                });
            }
            $(window).resize(function() {
                if ($(window).width() <= 767) {
                    $("._scroller ul").owlCarousel({
                        nav: false,
                        dots: true,
                        responsive: {
                            0: {
                                items: 1
                            }
                        }
                    });
                }
                else if ($(window).width() > 767) {
                    var sale = $('._scroller ul');
                    if(sale.hasClass('owl-carousel')) {
                        sale.trigger('destroy.owl.carousel').removeClass('owl-carousel owl-loaded');
                        sale.find('.owl-stage-outer').children().unwrap();
                    }
                }
            });
		});
    </script>

<?php endif; ?>

